### Getting all People
GET localhost:8080/api/people

### Creating a new Person
POST localhost:8080/api/people
Content-Type: application/json

{
    "name": "Simon",
    "email": "simon@test.se",
    "birthDate": "2020-01-01"
}

### Creating a new Person - FAILING
POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "S",
  "email": "s",
  "birthDate": "2020-01-01"
}


### Get by Id - Not okey
GET localhost:8080/api/people/-65

### Get by Id - Triggers our custom Exceptipon handler 🫡
GET localhost:8080/api/people/65
