spring:
  application:
    name: g58-todo-app
  datasource:
    url: jdbc:mysql://localhost:3306/g58-todo-app?createDatabaseIfNotExist=true
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 60000
      max-lifetime: 1200000
      keepalive-time: 60000
      connection-timeout: 5000
      leak-detection-threshold: 2000
      pool-name: HikariPool-DEV
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

